### ISSUE TITLE
create code for even odd number display in java

### ISSUE THREAD

**Issue by Such6** [Such6/mycode#1]

**Comment by priyanshi-git** [comment]
Can you explain what needs to be done a little more ? I would like to work on this ?

**Comment by Hussain6** [comment]
@Such6 Can you assign this issue to me I would like to contribute to it with even & odd number code in java.

**Comment by satyam2k3** [comment]
Can you assign this issue to me I would like to work on this.

**Comment by rishabhknowss** [comment]
please assign me the task

**Comment by sohamgupta100** [comment]
@Such6 please assign the task to me!
